version: 2
updates:
  - package-ecosystem: "pip"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
  - package-ecosystem: "github-actions"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
